using Content.Shared.Clothing;
using Content.Shared.CMU14.PersistentEconomy; // CMU14
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutContainer : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;

    private readonly EntityUid? _entity;
    private long _cmuPrice; // CMU14
    private string? _text; // CMU14

    public Button Select => SelectButton;
    public Button Remove => RemoveButton;

    public bool IsSelected { get; set; }

    public string? Text
    {
        get => _text; // CMU14
        set // CMU14 start
        {
            _text = value;
            SelectButton.Text = _cmuPrice > 0 && !string.IsNullOrEmpty(value)
                ? $"{value} — ${_cmuPrice}"
                : value;
        } // CMU14 end
    }

    public LoadoutContainer(ProtoId<LoadoutPrototype> proto, bool disabled, FormattedMessage? reason, bool repeatable = false)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SelectButton.Disabled = disabled;
        SelectButton.ToggleMode = !repeatable;

        if (disabled && reason != null)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(reason);
            SelectButton.TooltipSupplier = _ => tooltip;
        }

        if (_protoManager.Resolve(proto, out var loadProto))
        {
            var ent = loadProto.DummyEntity ?? _entManager.System<LoadoutSystem>().GetFirstOrNull(loadProto);

            if (ent == null)
                return;

            // CMU14 start - Persistent economy prices belong on the existing loadout UI.
            foreach (var pricedItem in _protoManager.EnumeratePrototypes<CMULoadoutItemPrototype>())
            {
                if (pricedItem.Entity != ent.Value || pricedItem.Price <= 0)
                    continue;

                _cmuPrice = pricedItem.Price;
                break;
            }
            // CMU14 end

            _entity = _entManager.SpawnEntity(ent, MapCoordinates.Nullspace);
            Sprite.SetEntity(_entity);

            var spriteTooltip = new Tooltip();
            spriteTooltip.SetMessage(FormattedMessage.FromUnformatted(_entManager.GetComponent<MetaDataComponent>(_entity.Value).EntityDescription));

            TooltipSupplier = _ => spriteTooltip;
        }
    }

    [System.Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _entManager.DeleteEntity(_entity);
    }
}
