namespace Content.Shared.CMU.Round;

/// <summary>
/// Identifies a force-neutral purpose fulfilled by one mapped round-setup endpoint.
/// Side ownership and force-specific content are resolved separately from this semantic identity.
/// </summary>
public enum RoundSetupSlot : byte
{
    None,
    CorpsmanVendor,
    ClothingVendor,
    ShipsideUniformVendor,
    WeaponsVendor,
    SpecialWeaponsVendor,
    ObjectivesConsole,
    ObjectiveReturnPoint,
    DropshipWeaponsConsole,
    DropshipNavigationConsole,
    DropshipDestination,
    FighterDestination,
    RequisitionsLift,
    RequisitionsConsole,
    AutomaticRiflemanVendor,
    RiflemanVendor,
    DropshipCrewChiefVendor,
    OperationsOfficerVendor,
    RadioTelephoneOperatorVendor,
    JuniorOfficerVendor,
    MilitaryPoliceVendor,
    MilitaryDoctorVendor,
    SectionSergeantVendor,
    SquadSergeantVendor,
    PilotVendor,
    CombatTechnicianVendor,
    LockedFtlDoor,
    LockedFtlGlassDoor,
    LockedCommandDoor,
    LockedSecurityDoor,
    LockedSecurityGlassDoor,
    LockedGlassDoor,
    LockedCommandGlassDoor,
    LockedNormalDoor,
    LockedEngineeringDoor,
    LockedEngineeringGlassDoor,
    LockedMedicalDoor,
    LockedMedicalGlassDoor,
    OverwatchConsole,
    IntelligenceComputer,
    TechnologyTreeConsole,
    GroundsideOperationsConsole,
    TacticalMap,
    RequisitionsVendor,
    VehicleCrewVendor,
    Analyzer,
    AiCore,
    AllianceConsole,
    OrbitalCannon,
    WithdrawalConsole,
    CommandTablet,
    LockedDoubleNormalDoor,
    LockedDoubleGlassDoor,
    LockedDoubleCommandDoor,
    LockedDoubleCommandGlassDoor,
    LockedDoubleSecurityDoor,
    LockedDoubleSecurityGlassDoor,
    LockedDoubleMedicalDoor,
    LockedDoubleMedicalGlassDoor,
    LockedDoubleEngineeringDoor,
    LockedDoubleEngineeringGlassDoor,
    LockedLogisticsDoor,
    LockedLogisticsGlassDoor,
    LockedDoubleLogisticsDoor,
    LockedDoubleLogisticsGlassDoor,
    CallsignLaptop,
    ShipCommunicationsArray,
    RosterConsole,
}
