- type: job
  parent: CMJobBase
  id: AU14JobCivilianColonySynthetic
  name: au14-job-name-civiliancolonysynthetic
  description: au14-job-description-civiliancolonysynthetic
  setPreference: true
  playTimeTracker: AU14JobCivilianColonySynthetic
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianColonySynthetic
  icon: "CMJobIconEmpty"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 5
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        RMCSkillFirearms: 2
        RMCSkillOverwatch: 1
        RMCSkillMedical: 4
        RMCSkillSurgery: 3
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 5
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 3
        RMCSkillIntel: 2
        RMCSkillDomestics: 2
        RMCSkillNavigations: 1
    - type: JobPrefix
      prefix: au14-job-prefix-civiliancolonysynthetic
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianColonySynthetic
  equipment:
    jumpsuit: RMCJumpsuitCivilian
    shoes: RMCBootsCorporate
    id: CMIDCardColonist
    ears: CMHeadsetColony
  inhand:
  - RMCSmartpackBlack

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianColonySynthetic
  name: Spawn Point AU14 Colony Synthetic
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonySynthetic
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianColonySynthetic
  isHumanoid: true
