- type: job
  parent: CMJobBase
  id: AU14JobCivilianMiner
  name: au14-job-name-civilianminer
  description: au14-job-description-civilianminer
  setPreference: true
  playTimeTracker: AU14JobCivilianMiner
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianMiner
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-foreman
  accessGroups:
  - Colonist
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 2
        RMCSkillVehicles: 2
        RMCSkillDomestics: 1
        RMCSkillFirearms: 1
    - type: JobPrefix
      prefix: au14-job-prefix-civilianminer
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianMiner
  equipment:
    jumpsuit: AU14CivilianKellandMiningClothes
    outerClothing: AU14CivilianHazardVestKellandMiningCorporation
    shoes: RMCBootsCorporate
    id: AU14IDCardColonyColonist

    head: RMCHardhatOrange

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianMiner
  name: Spawn Point Civilian Miner
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianMiner
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianMiner
  isHumanoid: true
