- type: job
  parent: CMJobBase
  id: AU14Jobmobgoon
  name: au14-job-name-mobgoon
  description: au14-job-description-mobgoon
  setPreference: true
  playTimeTracker: AU14Jobmobgoon
  startingGear: AU14GearMobgoon
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-mobgoon
  accessGroups:
  - aumob
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillFirearms: 1
    - type: JobPrefix
      prefix: au14-job-prefix-mobboss
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearMobgoon
  equipment:
    jumpsuit: CMJumpsuitLiaisonCharcoal
    shoes: RMCShoesLaceup
    id: AU14IDCardmobgoon
    ears: AUheadsetmob

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointmobgoon
  name: Spawn Point Mob goon
  components:
  - type: SpawnPoint
    job_id: AU14Jobmobgoon
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14Jobmobgoon
  isHumanoid: true
