// RMC14
using Content.Client._RMC14.Chat;
// RMC14
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared.CCVar;
using Content.Shared.Chat;
using Content.Shared.Input;
using Content.Shared.Radio;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private ILogManager _log = default!;
    [Dependency] private IConfigurationManager _config = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;
    private readonly Dictionary<string, ChatTabButton> _tabButtons = new();
    private readonly Dictionary<string, int> _tabUnread = new();
    private readonly List<ChatTabSettings> _overflowTabs = new();
    private List<ChatTabSettings> _tabs = new();
    private List<ChatStyleSettings> _styles = new();
    private IReadOnlyList<ChatStyleTarget> _styleTargets = Array.Empty<ChatStyleTarget>();
    private IReadOnlyList<ChatRadioTarget> _radioTargets = Array.Empty<ChatRadioTarget>();
    private string _activeTabId = ChatUserSettings.AllTabId;
    private string _secondaryTabId = ChatUserSettings.RadioTabId;
    private string? _draggingTabId;
    private string? _dragTargetTabId;
    private bool _splitChatEnabled;
    private bool _splitAvailable = true;
    private bool _legacyChatEnabled;
    private bool _forceLegacyPresentation;
    private bool _colorWholeMessage;
    private ChatChannel _legacyChannelMask = (ChatChannel) ushort.MaxValue;
    private int _secondaryRatioPercent = ChatUserSettings.DefaultSplitSecondaryRatioPercent;
    private bool _syncingFilter;
    private bool LegacyPresentation => _forceLegacyPresentation || _legacyChatEnabled;
    private static readonly Color StructuredMessageTextColor = Color.FromHex("#D6DCE0");

    public bool Main { get; set; }

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    public void SetSplitAvailable(bool available)
    {
        _splitAvailable = available;
        SplitButton.Visible = available && !LegacyPresentation;
        if (!available)
        {
            SplitButton.Popup.Close();
            SetSplitChatEnabled(false, save: false);
            return;
        }

        SyncSplitControls();
    }

    public void SetForceLegacyPresentation(bool forced)
    {
        var wasLegacy = LegacyPresentation;
        if (_forceLegacyPresentation == forced)
            return;

        _forceLegacyPresentation = forced;
        if (!wasLegacy && LegacyPresentation)
            ResetLegacyChannelMask();

        ApplyChatMode();
        Repopulate();
    }

    // RMC14
    public readonly Queue<RepeatedMessage> RepeatQueue = new();
    // RMC14
    private readonly HashSet<string> _whitelist = ["mono", "scramble", "bolditalic", "bold", "bullet", "color", "font", "head", "italic", "langicon"];
    // RMC14

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        ChatInput.FilterButton.Popup.OnTabSelected += OnSettingsTabSelected;
        ChatInput.FilterButton.Popup.OnTabAdded += OnSettingsTabAdded;
        ChatInput.FilterButton.Popup.OnTabRemoved += OnSettingsTabRemoved;
        ChatInput.FilterButton.Popup.OnTabRenamed += OnSettingsTabRenamed;
        ChatInput.FilterButton.Popup.OnTabMoved += OnSettingsTabMoved;
        ChatInput.FilterButton.Popup.OnRadioFilter += OnSettingsRadioFilter;
        ChatInput.FilterButton.Popup.OnStyleChanged += OnSettingsStyleChanged;
        ChatInput.FilterButton.Popup.OnStyleReset += OnSettingsStyleReset;
        ChatInput.FilterButton.Popup.OnColorWholeMessageChanged += OnSettingsColorWholeMessageChanged;
        ChatInput.FilterButton.Popup.OnLegacyModeChanged += OnSettingsLegacyModeChanged;
        SplitButton.Popup.OnTabSelected += OnSplitTabSelected;
        TabOverflowButton.Popup.OnTabSelected += OnOverflowTabSelected;
        SecondaryResizeHandle.OnDragged += OnSplitResizeDragged;
        SecondaryResizeHandle.OnDragEnded += OnSplitResizeEnded;
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.FilterableChannelsChanged += OnFilterableChannelsChanged;
        _controller.RegisterChat(this);
        _config.OnValueChanged(CCVars.ChatLegacyMode, OnLegacyModeCvarChanged);
        _config.OnValueChanged(CCVars.ChatColorWholeMessage, OnColorWholeMessageCvarChanged);

        _tabs = ChatUserSettings.LoadTabs(_config.GetCVar(CCVars.ChatTabs));
        _styles = ChatUserSettings.LoadStyles(_config.GetCVar(CCVars.ChatChannelStyles));
        var split = ChatUserSettings.LoadSplitPane(_config.GetCVar(CCVars.ChatSplitPane));
        _splitChatEnabled = split.Enabled;
        _secondaryTabId = split.SecondaryTabId;
        _secondaryRatioPercent = split.SecondaryRatioPercent;
        _legacyChatEnabled = _config.GetCVar(CCVars.ChatLegacyMode);
        _colorWholeMessage = _config.GetCVar(CCVars.ChatColorWholeMessage);
        var radioChannels = _prototype.EnumeratePrototypes<RadioChannelPrototype>().ToList();
        _styleTargets = ChatUserSettings.CreateStyleTargets(radioChannels);
        _radioTargets = ChatUserSettings.CreateRadioTargets(radioChannels);

        RebuildTabs();
        SetActiveTab(_activeTabId, repopulate: false);
        SetSplitChatEnabled(_splitChatEnabled, repopulate: false, save: false);
        ApplyChatMode();
        Repopulate();
    }

    protected override void Resized()
    {
        base.Resized();
        UpdateTabOverflowControls();
        RefreshVisibleChatLayout();
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        DisplayMessage(msg, fromHistory: false);
    }

    private void DisplayMessage(ChatMessage msg, bool fromHistory)
    {
        if (LegacyPresentation)
        {
            var visible = IsMessageVisibleInLegacy(msg);
            if (visible)
                AddLegacyLine(msg);

            if (fromHistory || !visible)
                return;

            if (msg is { Read: false, AudioPath: { } })
                _entManager.System<AudioSystem>().PlayGlobal(new ResolvedPathSpecifier(msg.AudioPath), Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

            msg.Read = true;
            return;
        }

        if (fromHistory)
        {
            if (IsMessageVisibleInActiveTab(msg))
                AddLine(msg, Contents, _primaryRepeatQueue);

            if (IsMessageVisibleInSecondaryTab(msg))
                AddLine(msg, SecondaryContents, _secondaryRepeatQueue);

            return;
        }

        if (!IsMessageVisibleInAnyPage(msg))
            return;

        if (msg is { Read: false, AudioPath: { } })
            _entManager.System<AudioSystem>().PlayGlobal(new ResolvedPathSpecifier(msg.AudioPath), Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        UpdateInactiveTabUnreads(msg);

        // RMC14
        AddLine(msg.WrappedMessage, color, msg.SenderEntity, msg.Message, msg.Channel, msg.RepeatCheckSender, msg.LanguageIcon);
        // RMC14
    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        if (LegacyPresentation)
        {
            LegacyContents.Clear();
            _legacyRepeatQueue.Clear();

            foreach (var message in _controller.History)
            {
                if (IsMessageVisibleInLegacy(message.Item2))
                    AddLegacyLine(message.Item2);
            }

            LegacyContents.ScrollToBottom();
            return;
        }

        Contents.Clear();
        _primaryRepeatQueue.Clear();

        foreach (var message in _controller.History)
        {
            if (IsMessageVisibleInActiveTab(message.Item2))
                AddLine(message.Item2, Contents, _primaryRepeatQueue);
        }

        Contents.ScrollToBottom();

        if (_splitChatEnabled)
            RepopulateSecondary();
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        if (_syncingFilter)
            return;

        if (LegacyPresentation)
        {
            _legacyChannelMask = active
                ? _legacyChannelMask | channel
                : _legacyChannelMask & ~channel;

            Repopulate();

            if (active)
                _controller.ClearUnfilteredUnreads(channel);

            return;
        }

        var tab = GetActiveTab();
        if (IsAllTab(tab))
            return;

        tab.ChannelMask = active
            ? tab.ChannelMask | channel
            : tab.ChannelMask & ~channel;
        SaveTabs();

        Repopulate();

        if (active)
            _controller.ClearUnfilteredUnreads(channel);
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    // RMC14
    public void AddLine(
        string message,
        Color color,
        NetEntity sender,
        string unwrapped,
        ChatChannel channel,
        bool repeatCheckSender,
        string? languageIcon = null)
    // RMC14
    {
        var msg = new ChatMessage(
            channel,
            unwrapped,
            message,
            sender,
            null,
            colorOverride: color,
            repeatCheckSender: repeatCheckSender,
            display: new ChatDisplayMetadata(ChatDisplayKind.System, channelLabel: "SYS"));

        AddLine(msg);
    }

    private FormattedMessage CreateFormattedMessage(ChatMessage message, Color color, ChatStyleSettings? style = null)
    {
        var markup = StripDuplicateChannelPrefix(message.WrappedMessage, message);
        markup = _colorWholeMessage
            ? ChatUserSettings.ApplyStyleMarkup(markup, style, ChatUserSettings.DefaultFontSize)
            : ChatUserSettings.ApplyFontMarkup(RemoveOuterColorMarkup(markup), style, ChatUserSettings.DefaultFontSize);

        var formatted = new FormattedMessage(3);
        if (_colorWholeMessage)
            formatted.PushColor(color);

        formatted.AddMarkupOrThrow(markup);

        if (_colorWholeMessage)
            formatted.Pop();

        return FilterProblematicTags(formatted);
    }

    private static string RemoveOuterColorMarkup(string markup)
    {
        if (!markup.StartsWith("[color=", StringComparison.OrdinalIgnoreCase) ||
            !markup.EndsWith("[/color]", StringComparison.OrdinalIgnoreCase))
        {
            return markup;
        }

        var openEnd = markup.IndexOf(']');
        if (openEnd < 0)
            return markup;

        return markup.Substring(openEnd + 1, markup.Length - openEnd - "[/color]".Length - 1);
    }

    private FormattedMessage CreateLegacyFormattedMessage(ChatMessage message, Color color)
    {
        var formatted = new FormattedMessage(3);
        formatted.PushColor(color);
        // RMC14
        if (!string.IsNullOrWhiteSpace(languageIcon))
            formatted.AddMarkupOrThrow($"[langicon path=\"{FormattedMessage.EscapeText(languageIcon)}\"][/langicon]");
        // RMC14
        formatted.AddMarkupOrThrow(message);
        formatted.Pop();

        // RMC14
        formatted = FilterProblematicTags(formatted);
        if (_entManager.SystemOrNull<CMChatSystem>()?.TryRepetition(this, Contents, formatted, sender, unwrapped, channel, repeatCheckSender, languageIcon) ?? false)
            return;

    private static string StripDuplicateChannelPrefix(string markup, ChatMessage message)
    {
        if (!string.IsNullOrWhiteSpace(message.Display?.ChannelLabel))
        {
            var label = message.Display.ChannelLabel.ToUpperInvariant();
            markup = StripVisiblePrefix(markup, $"{label}: ");
            markup = StripVisiblePrefix(markup, $"{label} ");

            if (message.Channel == ChatChannel.Radio)
            {
                markup = StripVisiblePrefix(markup, $@"\[{message.Display.ChannelLabel}\] ");
                markup = StripVisiblePrefix(markup, $"[{message.Display.ChannelLabel}] ");
            }
        }

        switch (message.Channel)
        {
            case ChatChannel.OOC:
                return StripVisiblePrefix(markup, "OOC: ");
            case ChatChannel.LOOC:
                return StripVisiblePrefix(markup, "LOOC: ");
            case ChatChannel.Dead:
                return StripVisiblePrefix(markup, "DEAD: ");
            case ChatChannel.Admin:
            case ChatChannel.AdminAlert:
            case ChatChannel.AdminChat:
                markup = StripVisiblePrefix(markup, "ADMIN: ");
                return StripVisiblePrefix(markup, "ASAY: ");
            case ChatChannel.MentorChat:
                return StripVisiblePrefix(markup, "MENTOR: ");
            default:
                return markup;
        }
    }

    private static string StripVisiblePrefix(string markup, string prefix)
    {
        var index = GetVisibleTextStart(markup);
        if (index < 0 || index + prefix.Length > markup.Length)
            return markup;

        if (!markup.Substring(index, prefix.Length).Equals(prefix, StringComparison.OrdinalIgnoreCase))
            return markup;

        return markup.Remove(index, prefix.Length);
    }

    private static int GetVisibleTextStart(string markup)
    {
        var index = 0;
        while (index < markup.Length && markup[index] == '[')
        {
            if (index + 1 < markup.Length && markup[index + 1] == '/')
                break;

            var end = markup.IndexOf(']', index);
            if (end < 0)
                break;

            index = end + 1;
        }

        return index;
    }

    // RMC14
    private FormattedMessage FilterProblematicTags(FormattedMessage message)
    {
        var output = new FormattedMessage(message.Count);
        foreach (var tag in message)
        {
            if (tag.Name is not { } name || _whitelist.Contains(name))
                output.PushTag(tag);
        }
        return output;
    }
    // RMC14

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            // go over every channel until we find one we can actually select.
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        // Update channel select button to correct channel if we have a prefix.
        _controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        _controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(false);
    }

    [System.Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing) return;
        _controller.UnregisterChat(this);
        _controller.MessageAdded -= OnMessageAdded;
        _controller.HighlightsUpdated -= OnHighlightsUpdated;
        _controller.FilterableChannelsChanged -= OnFilterableChannelsChanged;
        _config.UnsubValueChanged(CCVars.ChatLegacyMode, OnLegacyModeCvarChanged);
        _config.UnsubValueChanged(CCVars.ChatColorWholeMessage, OnColorWholeMessageCvarChanged);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.Input.OnFocusEnter -= OnFocusEnter;
        ChatInput.Input.OnFocusExit -= OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter -= OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights -= OnNewHighlights;
        ChatInput.FilterButton.Popup.OnTabSelected -= OnSettingsTabSelected;
        ChatInput.FilterButton.Popup.OnTabAdded -= OnSettingsTabAdded;
        ChatInput.FilterButton.Popup.OnTabRemoved -= OnSettingsTabRemoved;
        ChatInput.FilterButton.Popup.OnTabRenamed -= OnSettingsTabRenamed;
        ChatInput.FilterButton.Popup.OnTabMoved -= OnSettingsTabMoved;
        ChatInput.FilterButton.Popup.OnRadioFilter -= OnSettingsRadioFilter;
        ChatInput.FilterButton.Popup.OnStyleChanged -= OnSettingsStyleChanged;
        ChatInput.FilterButton.Popup.OnStyleReset -= OnSettingsStyleReset;
        ChatInput.FilterButton.Popup.OnColorWholeMessageChanged -= OnSettingsColorWholeMessageChanged;
        ChatInput.FilterButton.Popup.OnLegacyModeChanged -= OnSettingsLegacyModeChanged;
        SplitButton.Popup.OnTabSelected -= OnSplitTabSelected;
        TabOverflowButton.Popup.OnTabSelected -= OnOverflowTabSelected;
        SecondaryResizeHandle.OnDragged -= OnSplitResizeDragged;
        SecondaryResizeHandle.OnDragEnded -= OnSplitResizeEnded;
    }
}
