using Content.Shared.CMU14.Administration.Tickets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Administration.Tickets;

/// <summary>
/// Asks for the close reason. Confirm stays disabled until the reason has text; the server checks again.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CMUTicketCloseWindow : DefaultWindow
{
    public event Action<string>? OnConfirm;

    public CMUTicketCloseWindow()
    {
        RobustXamlLoader.Load(this);

        ReasonEdit.IsValid = text => text.Length <= CMUTicketLimits.MaxCloseReasonLength;
        ReasonEdit.OnTextChanged += args => ConfirmButton.Disabled = string.IsNullOrWhiteSpace(args.Text);
        ReasonEdit.OnTextEntered += _ => Confirm();
        ConfirmButton.OnPressed += _ => Confirm();
    }

    private void Confirm()
    {
        var reason = ReasonEdit.Text.Trim();
        if (reason.Length == 0)
            return;

        OnConfirm?.Invoke(reason);
        Close();
    }
}
