using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Content.Server.Database.Migrations.Postgres
{
    /// <inheritdoc />
    public partial class RMCFix : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Some CMU databases applied this table under the old RMCRankPreference migration ID.
            // Keep the replacement migration compatible with both those databases and fresh installs.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS rank (
                    rank_id integer GENERATED BY DEFAULT AS IDENTITY,
                    profile_id integer NOT NULL,
                    job_name text NOT NULL,
                    rank_name text NOT NULL,
                    CONSTRAINT "PK_rank" PRIMARY KEY (rank_id),
                    CONSTRAINT "FK_rank_profile_profile_id" FOREIGN KEY (profile_id) REFERENCES profile (profile_id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_rank_profile_id" ON rank (profile_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "rank");
        }
    }
}
