// CMU14 file: recreates the legacy wizden ban tables (dropped by BanRefactor) so upstream
// master, whose model still lives in them, can share a database with this branch. Intentionally
// empty and without FKs/indexes; Rebase reads/writes only the new ban* tables.
using Content.Server.Database;
using Microsoft.EntityFrameworkCore.Infrastructure; // CMU14
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Content.Server.Database.Migrations.Postgres
{
    [DbContext(typeof(PostgresServerDbContext))]
    [Migration("20260901120000_RecreateLegacyBanTables")]
    public sealed class RecreateLegacyBanTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS server_ban (
                    server_ban_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    address text,
                    auto_delete boolean NOT NULL,
                    ban_time timestamp with time zone NOT NULL,
                    banning_admin uuid,
                    exempt_flags integer NOT NULL,
                    expiration_time timestamp with time zone,
                    hidden boolean NOT NULL,
                    last_edited_at timestamp with time zone,
                    last_edited_by_id uuid,
                    player_user_id uuid,
                    playtime_at_note interval NOT NULL,
                    reason text NOT NULL,
                    round_id integer,
                    severity integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS server_unban (
                    unban_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ban_id integer NOT NULL,
                    unban_time timestamp with time zone NOT NULL,
                    unbanning_admin uuid
                );

                CREATE TABLE IF NOT EXISTS server_role_ban (
                    server_role_ban_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    address text,
                    ban_time timestamp with time zone NOT NULL,
                    banning_admin uuid,
                    expiration_time timestamp with time zone,
                    hidden boolean NOT NULL,
                    last_edited_at timestamp with time zone,
                    last_edited_by_id uuid,
                    player_user_id uuid,
                    playtime_at_note interval NOT NULL,
                    reason text NOT NULL,
                    role_id text NOT NULL,
                    round_id integer,
                    severity integer NOT NULL
                );

                CREATE TABLE IF NOT EXISTS server_role_unban (
                    role_unban_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ban_id integer NOT NULL,
                    unban_time timestamp with time zone NOT NULL,
                    unbanning_admin uuid
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
