using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Underground.BurrowerTunnel;

[GenerateTypedNameReferences]
public sealed partial class BurrowerTunnelWindow : DefaultWindow
{
    public BurrowerTunnelWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
