- type: job
  parent: CMJobBase
  id: AU14NEMOSynthetic
  name: au14-job-name-corp-nemo-sed-enforcer
  description: au14-job-description-corp-nemo-sed-synthetic
  playTimeTracker: AU14JobNEMOSynthetic
  ranks:
    AU14RankNEMOWO1: []
  startingGear: AU14GearNEMOSynthetic
  icon: AU14JobIconNEMOSynthetic
  joinNotifyCrew: false
  #  whitelisted: true # Free use synthetic, requires admin guidance
  accessGroups:
  - AllAccess
  spawnMenuRoleName: NEMO Synthetic
  special:
  - !type:AddComponentSpecial
    components:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14map_blips.rsi
        state: background_nemo
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Skills
      skills:
        RMCSkillCqc: 5
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        RMCSkillFirearms: 2
        RMCSkillOverwatch: 1
        RMCSkillMedical: 4
        RMCSkillSurgery: 3
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 1
        RMCSkillPolice: 5
        RMCSkillFireman: 5
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 1
        RMCSkillIntel: 1
        RMCSkillDomestics: 2
        RMCSkillNavigations: 1
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-synthetic
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 35
    - type: Synth
  hidden: false

- type: entity
  id: AU14RandomHumanoidNEMOSynthetic
  name: NEMO ghost role synthetic
  suffix: Ghostrole, Friendly, UNWL'd
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: RandomHumanoidSpawner
    settings: AU14NEMOSynthetic

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: AU14NEMOSynthetic
  components:
  - type: GhostRole
    name: au14-ghost-name-corp-nemo-synthetic
    description: au14-job-description-corp-nemo-synthetic
    rules: au14-ghost-role-information-nemo-rules
    reregister: false
    job: AU14NEMOSynthetic
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORMilitaryPoliceMan
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORAuxSupportSynth
      time: 3600 # 1 Hour
  - type: GhostRoleApplySpecial
    squad: AU14SquadNEMO

- type: startingGear
  id: AU14GearNEMOSynthetic
  equipment:
    head: RMCHeadBeretProvost
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvost
    outerClothing: RMCArmorProvost
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    suitstorage: WeaponShotgunM890
    id: RMCIDCardProvostEnforcer
    belt: RMCM1984BeltFilled
    back: CMSatchelSecurityFilledProvostEnforcer
    pocket1: RMCPouchShotgunLargeBeanbag
    pocket2: RMCPouchShotgunLargeSlugs # TODO RMC14 riot shield

- type: playTimeTracker
  id: AU14JobNEMOSynthetic

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconNEMOSynthetic
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_synth

# Grade 2

- type: job
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic2
  ranks:
    AU14RankNEMOWO2: []

- type: entity
  parent: AU14RandomHumanoidNEMOSynthetic
  id: AU14RandomHumanoidNEMOSynthetic2
  suffix: Ghostrole, Friendly, WL'd (No knowledge)

- type: randomHumanoidSettings
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic2

- type: jobIcon
  parent: AU14JobIconNEMOSynthetic
  id: AU14JobIconNEMOSynthetic2

# Grade 3

- type: job
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic3
  ranks:
    AU14RankNEMOWO3: []

- type: entity
  parent: AU14RandomHumanoidNEMOSynthetic
  id: AU14RandomHumanoidNEMOSynthetic3
  suffix: Ghostrole, Friendly, WL'd (Low Knowledge)

- type: randomHumanoidSettings
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic3

- type: jobIcon
  parent: AU14JobIconNEMOSynthetic
  id: AU14JobIconNEMOSynthetic3

# Grade 4

- type: job
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic4
  ranks:
    AU14RankNEMOWO4: []

- type: entity
  parent: AU14RandomHumanoidNEMOSynthetic
  id: AU14RandomHumanoidNEMOSynthetic4
  suffix: Ghostrole, Friendly, WL'd (Med Knowledge)

- type: randomHumanoidSettings
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic4

- type: jobIcon
  parent: AU14JobIconNEMOSynthetic
  id: AU14JobIconNEMOSynthetic4

# Grade 5

- type: job
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic5
  ranks:
    AU14RankNEMOWO2: []

- type: entity
  parent: AU14RandomHumanoidNEMOSynthetic
  id: AU14RandomHumanoidNEMOSynthetic5
  suffix: Ghostrole, Friendly, WL'd (High Knowledge)

- type: randomHumanoidSettings
  parent: AU14NEMOSynthetic
  id: AU14NEMOSynthetic5

- type: jobIcon
  parent: AU14JobIconNEMOSynthetic
  id: AU14JobIconNEMOSynthetic5
