- type: job
  parent: CMJobBase
  id: AU14JobGOVFORRadioTelephoneOperator
  name: au14-job-name-radiotelephoneoperator
  description: au14-job-description-radiotelephoneooerator
  setPreference: true
  playTimeTracker: AU14JobGOVFORRadioTelephoneOperator
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 3600 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 1800 # 30 hours
    RMCRankPrivateFirstClass: []
  startingGear: AU14GearGOVFORRadioTelephoneOperator
  dummyStartingGear: AU14GearGOVFORRadioTelephoneOperatorDummy
  icon: "AU14JobIconRTO"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - FTL
  overwatchSortPriority: -5
  overwatchRoleName: Radio Telephone Operator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-radiotelephoneoperator
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: false

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOperator
  equipment:
    id: AU14JobIDCardGOVFORRadioTelephoneOperator
    ears: AU14HeadsetSectionMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORRadioTelephoneOperator
  name: Spawn Point GOVFOR Radio Telephone Operator
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORRadioTelephoneOperator
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobGOVFORRadioTelephoneOperator
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOperatorDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionMarine
