- type: job
  parent: CMJobBase
  id: CMCommandingOfficer
  name: cm-job-name-commanding-officer
  description: cm-job-description-commanding-officer
  setPreference: false
  playTimeTracker: CMJobCommandingOfficer
  requirements: []
  ranks:
    RMCRankColonel:
    - !type:RoleTimeRequirement
      role: CMJobCommandingOfficer
      time: 630000 # 175 hours
    RMCRankLieutenantColonel:
    - !type:RoleTimeRequirement
      role: CMJobCommandingOfficer
      time: 252000 # 70 hours
    RMCRankMajor: []
  weight: 10
  startingGear: CMGearCommandingOfficer
  icon: "CMJobIconCommandingOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  marineAuthorityLevel: 15
  supervisors: cm-job-supervisors-marine-high-command
  whitelisted: true
  accessGroups:
  - ShipMasterAccess
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillExecution: 1
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSmartGun: 1
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: MarineOrders
    - type: CMVendorUser
      points: 120
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-commanding-officer
    - type: CommendationGiver
    - type: ViewIntelObjectives
    - type: CommandAccent
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: co
      background:
        sprite: _RMC14/Interface/map_blips.rsi
        state: background_command
    - type: RMCTrackable

- type: startingGear
  id: CMGearCommandingOfficer
  equipment:
    jumpsuit: CMJumpsuitBO
    shoes: CMShoesLaceupCommander
    head: CMHeadBeretCO
    outerClothing: RMCCoatService
    ears: CMHeadsetSeniorCommand
    pocket1: RMCPouchCommand
    pocket2: RMCPouchGeneralLarge
  inhand:
    - RMCMatebaCustomizationCase

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCommandingOfficer
  name: commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMCommandingOfficer
  - type: Sprite
    state: co_spawn

- type: playTimeTracker
  id: CMJobCommandingOfficer
  isHumanoid: true

- type: entity
  parent: CMGuidebookRole
  id: RMCGuidebookRoleCO
  name: The Commanding Officer
  description: The Commanding Officer.
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: commanding_officer
