- type: job
  parent: CMJobBase
  id: CMStaffOfficer
  name: cm-job-name-platoon-operations-officer
  description: cm-job-description-platoon-operations-officer
  setPreference: false
  playTimeTracker: CMJobStaffOfficer
  ranks:
    RMCRankSecondLT: []
  weight: 5
  startingGear: CMGearStaffOfficer
  icon: "CMJobIconStaffOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-platco
  accessGroups:
  - MarineMain
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 3
        RMCSkillLeadership: 2
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPolice: 1
        RMCSkillPowerLoader: 1
        RMCSkillSurgery: 1
        RMCSkillVehicles: 2
    - type: MarineOrders
    - type: CMVendorUser
      points: 45
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-staff-officer
    - type: ViewIntelObjectives
    - type: CommandAccent
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: so
      background:
        sprite: _RMC14/Interface/map_blips.rsi
        state: background_command

- type: startingGear
  id: CMGearStaffOfficer
  equipment:
    id: CMIDCardStaffOfficer

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointStaffOfficer
  name: staff officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMStaffOfficer
  - type: Sprite
    state: so_spawn

- type: playTimeTracker
  id: CMJobStaffOfficer
  isHumanoid: true

- type: entity
  parent: CMGuidebookRole
  id: RMCGuidebookRoleSO
  name: A Staff Officer
  description: A Staff Officer.
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: staff_officer
