- type: job
  parent: CMJobBase
  id: AU14SEDInspector
  name: au14-job-name-corp-nemo-sed-inspector
  description: au14-job-description-corp-nemo-sed-inspector
  playTimeTracker: AU14JobSEDInspector
  ranks:
    RMCRankProvostProvostEnforcer: []
  startingGear: AU14GearSEDInspector
  icon: AU14JobIconSEDInspector
  joinNotifyCrew: false
  accessGroups:
  - AllAccess
  spawnMenuRoleName: NEMO SED Inspector
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-enforcer
  hidden: true

- type: entity
  id: AU14RandomHumanoidSEDInspector
  name: NEMO SED ghost role inspector
  suffix: Ghostrole, Friendly
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: RandomHumanoidSpawner
    settings: AU14SEDInspector

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: AU14SEDInspector
  components:
  - type: GhostRole
    name: au14-ghost-name-corp-nemo-enforcer
    description: au14-job-description-corp-nemo-sed-inspector
    rules: au14-ghost-role-information-nemo-rules
    reregister: false
    job: AU14SEDInspector
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORMilitaryPoliceMan
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: AU14SquadSED

- type: startingGear
  id: AU14GearSEDInspector
  equipment:
    head: RMCHeadBeretProvost
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvost
    outerClothing: RMCArmorProvost
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    suitstorage: WeaponShotgunM890
    id: RMCIDCardProvostEnforcer
    belt: RMCM1984BeltFilled
    back: CMSatchelSecurityFilledProvostEnforcer
    pocket1: RMCPouchShotgunLargeBeanbag
    pocket2: RMCPouchShotgunLargeSlugs # TODO RMC14 riot shield

- type: playTimeTracker
  id: AU14JobSEDInspector

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconSEDInspector
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_lead_clear_blank
