using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private MarkingManager _marking = default!;

    private readonly HashSet<MarkingCategories> _ignoredCategories = [];
    private readonly HashSet<HumanoidVisualLayers> _ignoredLayers = [];
    private readonly List<MarkingCategories> _markingCategories = Enum.GetValues<MarkingCategories>().ToList();
    private readonly SpriteSystem _sprite;

    private HashSet<HumanoidVisualLayers>? _includedLayers;
    private MarkingCandidate? _selectedUnused;
    private MarkingCandidate? _selectedUsed;
    private MarkingsViewModel? _markingsModel;
    private MarkingCategories _selectedCategory = MarkingCategories.Chest;

    public string IgnoreCategories
    {
        get => string.Join(',', _ignoredCategories);
        set
        {
            _ignoredCategories.Clear();
            foreach (var category in value.Split(','))
            {
                if (Enum.TryParse<MarkingCategories>(category, out var parsed))
                    _ignoredCategories.Add(parsed);
            }

            UpdateMarkings();
        }
    }

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        CMarkingCategoryButton.OnItemSelected += OnCategoryChanged;
        CMarkingSearch.OnTextChanged += args => PopulateUnused(args.Text);
        CMarkingsUnused.OnItemSelected += args =>
        {
            _selectedUnused = CMarkingsUnused[args.ItemIndex].Metadata as MarkingCandidate;
            UpdatePoints(_selectedUnused);
        };
        CMarkingsUsed.OnItemSelected += OnUsedMarkingSelected;
        CMarkingAdd.OnPressed += _ => AddMarking();
        CMarkingRemove.OnPressed += _ => RemoveMarking();
        CMarkingRankUp.OnPressed += _ => ChangeRank(1);
        CMarkingRankDown.OnPressed += _ => ChangeRank(-1);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        UnsubscribeModel();
        _markingsModel = model;
        SubscribeModel();
        UpdateMarkings();
    }

    public void SetIncludedLayers(params HumanoidVisualLayers[] layers)
    {
        _includedLayers = [.. layers];
        UpdateMarkings();
    }

    public void SetIgnoredLayers(params HumanoidVisualLayers[] layers)
    {
        _ignoredLayers.Clear();
        _ignoredLayers.UnionWith(layers);
        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        SubscribeModel();
        UpdateMarkings();
    }

    protected override void ExitedTree()
    {
        UnsubscribeModel();
        base.ExitedTree();
    }

    private void SubscribeModel()
    {
        if (_markingsModel is null || !IsInsideTree)
            return;

        _markingsModel.OrganDataChanged -= UpdateMarkings;
        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
        _markingsModel.MarkingsReset -= UpdateMarkings;
        _markingsModel.MarkingsReset += UpdateMarkings;
        _markingsModel.MarkingsChanged -= OnMarkingsChanged;
        _markingsModel.MarkingsChanged += OnMarkingsChanged;
    }

    private void UnsubscribeModel()
    {
        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged -= UpdateMarkings;
        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
        _markingsModel.MarkingsReset -= UpdateMarkings;
        _markingsModel.MarkingsChanged -= OnMarkingsChanged;
    }

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateMarkings();
    }

    private void OnMarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        UpdateLists();
    }

    private void UpdateMarkings()
    {
        SetupCategoryButton();
        UpdateLists();
    }

    private void SetupCategoryButton()
    {
        CMarkingCategoryButton.Clear();
        var available = _markingCategories
            .Where(category => !_ignoredCategories.Contains(category) && GetCandidates(category).Count != 0)
            .ToList();

        foreach (var category in available)
        {
            CMarkingCategoryButton.AddItem(
                Loc.GetString($"markings-category-{category}"),
                (int) category);
        }

        if (available.Count == 0)
            return;

        if (!available.Contains(_selectedCategory))
            _selectedCategory = available[0];

        CMarkingCategoryButton.SelectId((int) _selectedCategory);
    }

    private void OnCategoryChanged(OptionButton.ItemSelectedEventArgs args)
    {
        CMarkingCategoryButton.SelectId(args.Id);
        _selectedCategory = (MarkingCategories) args.Id;
        UpdateLists();
    }

    private void UpdateLists()
    {
        PopulateUnused(CMarkingSearch.Text);
        PopulateUsed();
        CMarkingColors.Visible = false;
        CMarkingColors.DisposeAllChildren();
        _selectedUsed = null;
        UpdatePoints(null);
    }

    private void PopulateUnused(string filter)
    {
        CMarkingsUnused.Clear();
        _selectedUnused = null;

        foreach (var candidate in GetCandidates(_selectedCategory)
                     .Where(candidate => !candidate.Selected)
                     .Where(candidate => GetMarkingName(candidate.Prototype)
                         .Contains(filter, StringComparison.OrdinalIgnoreCase))
                     .OrderBy(candidate => GetMarkingName(candidate.Prototype)))
        {
            var item = CMarkingsUnused.AddItem(
                GetMarkingName(candidate.Prototype),
                _sprite.Frame0(candidate.Prototype.Sprites[0]));
            item.Metadata = candidate;
        }
    }

    private void PopulateUsed()
    {
        CMarkingsUsed.Clear();
        if (_markingsModel is null)
            return;

        foreach (var candidate in GetCandidates(_selectedCategory)
                     .Where(candidate => candidate.Selected)
                     .Reverse())
        {
            var marking = _markingsModel.GetMarking(candidate.Organ, candidate.Layer, candidate.Prototype.ID);
            var item = CMarkingsUsed.AddItem(
                GetMarkingName(candidate.Prototype),
                _sprite.Frame0(candidate.Prototype.Sprites[0]));
            item.Metadata = candidate;
            if (marking is { MarkingColors.Count: > 0 })
                item.IconModulate = marking.Value.MarkingColors[0];
        }
    }

    private List<MarkingCandidate> GetCandidates(MarkingCategories category)
    {
        var result = new List<MarkingCandidate>();
        if (_markingsModel is null)
            return result;

        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            if (!_markingsModel.OrganProfileData.TryGetValue(organ, out var profileData))
                continue;

            foreach (var layer in organData.Layers)
            {
                if ((_includedLayers is not null && !_includedLayers.Contains(layer)) ||
                    _ignoredLayers.Contains(layer) ||
                    MarkingCategoriesConversion.FromHumanoidVisualLayers(layer) != category)
                    continue;

                var markings = _markingsModel.EnforceGroupAndSexRestrictions
                    ? _marking.MarkingsByLayerAndGroupAndSex(layer, organData.Group, profileData.Sex)
                    : _marking.MarkingsByLayer(layer);

                foreach (var prototype in markings.Values)
                {
                    result.Add(new MarkingCandidate(
                        organ,
                        layer,
                        prototype,
                        _markingsModel.IsMarkingSelected(organ, layer, prototype.ID)));
                }
            }
        }

        return result;
    }

    private void AddMarking()
    {
        if (_markingsModel is null || _selectedUnused is not { } candidate)
            return;

        _markingsModel.TrySelectMarking(candidate.Organ, candidate.Layer, candidate.Prototype.ID);
    }

    private void RemoveMarking()
    {
        if (_markingsModel is null || _selectedUsed is not { } candidate)
            return;

        _markingsModel.TryDeselectMarking(candidate.Organ, candidate.Layer, candidate.Prototype.ID);
    }

    private void ChangeRank(int direction)
    {
        if (_markingsModel is null || _selectedUsed is not { } candidate ||
            _markingsModel.SelectedMarkings(candidate.Organ, candidate.Layer) is not { } markings)
            return;

        var index = markings.FindIndex(marking => marking.MarkingId == candidate.Prototype.ID);
        var target = index + direction;
        if (index < 0 || target < 0 || target >= markings.Count)
            return;

        _markingsModel.ChangeMarkingOrder(
            candidate.Organ,
            candidate.Layer,
            candidate.Prototype.ID,
            direction > 0 ? CandidatePosition.After : CandidatePosition.Before,
            target);
    }

    private void OnUsedMarkingSelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedUsed = CMarkingsUsed[args.ItemIndex].Metadata as MarkingCandidate;
        CMarkingColors.DisposeAllChildren();
        CMarkingColors.Visible = false;

        if (_markingsModel is null || _selectedUsed is not { } candidate ||
            !_markingsModel.IsMarkingColorCustomizable(candidate.Organ, candidate.Layer, candidate.Prototype.ID) ||
            _markingsModel.GetMarking(candidate.Organ, candidate.Layer, candidate.Prototype.ID) is not { } marking)
            return;

        CMarkingColors.Visible = true;
        for (var i = 0; i < candidate.Prototype.Sprites.Count; i++)
        {
            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            var selector = new ColorSelectorSliders
            {
                SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
                Color = marking.MarkingColors[i],
            };
            container.AddChild(new Label { Text = GetMarkingStateName(candidate.Prototype, i) });
            container.AddChild(selector);
            CMarkingColors.AddChild(container);

            var colorIndex = i;
            selector.OnColorChanged += color => _markingsModel.TrySetMarkingColor(
                candidate.Organ,
                candidate.Layer,
                candidate.Prototype.ID,
                colorIndex,
                color);
        }

        UpdatePoints(candidate);
    }

    private void UpdatePoints(MarkingCandidate? candidate)
    {
        CMarkingPoints.Visible = false;
        if (_markingsModel is null || candidate is not { } selected)
            return;

        _markingsModel.GetMarkingCounts(selected.Organ, selected.Layer, out _, out var count, out var used);
        if (count < 0)
            return;

        CMarkingPoints.Visible = true;
        CMarkingPoints.Text = Loc.GetString("marking-points-remaining", ("points", Math.Max(0, count - used)));
    }

    private string GetMarkingName(MarkingPrototype marking)
    {
        return Loc.GetString($"marking-{marking.ID}");
    }

    private string GetMarkingStateName(MarkingPrototype marking, int index)
    {
        return marking.Sprites[index] switch
        {
            SpriteSpecifier.Rsi rsi => Loc.GetString($"marking-{marking.ID}-{rsi.RsiState}"),
            SpriteSpecifier.Texture texture => Loc.GetString($"marking-{marking.ID}-{texture.TexturePath.Filename}"),
            _ => GetMarkingName(marking),
        };
    }

    private sealed record MarkingCandidate(
        ProtoId<OrganCategoryPrototype> Organ,
        HumanoidVisualLayers Layer,
        MarkingPrototype Prototype,
        bool Selected);
}
