using System.Linq;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;
    private HashSet<HumanoidVisualLayers>? _includedLayers;
    private readonly HashSet<HumanoidVisualLayers> _ignoredLayers = [];

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        if (_markingsModel is not null && IsInsideTree)
        {
            _markingsModel.OrganDataChanged -= UpdateMarkings;
            _markingsModel.EnforcementsChanged -= UpdateMarkings;
        }

        _markingsModel = model;

        if (IsInsideTree)
        {
            _markingsModel.OrganDataChanged += UpdateMarkings;
            _markingsModel.EnforcementsChanged += UpdateMarkings;
        }

        UpdateMarkings();
    }

    public void SetIncludedLayers(params HumanoidVisualLayers[] layers)
    {
        _includedLayers = [.. layers];
        UpdateMarkings();
    }

    public void SetIgnoredLayers(params HumanoidVisualLayers[] layers)
    {
        _ignoredLayers.Clear();
        _ignoredLayers.UnionWith(layers);
        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
        UpdateMarkings();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganTabs.RemoveAllChildren();

        var i = 0;
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            var layers = organData.Layers
                .Where(layer => (_includedLayers?.Contains(layer) ?? true) && !_ignoredLayers.Contains(layer))
                .ToHashSet();
            var control = new OrganMarkingPicker(_markingsModel, organ, layers, organData.Group);
            if (control.Empty)
                continue;

            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(i, Loc.GetString($"markings-organ-{organ.Id}"));
            i++;
        }

        if (i > 0)
            OrganTabs.CurrentTab = 0;
        OrganTabs.TabsVisible = i > 1;
    }
}
