- type: job
  parent: CMJobBase
  id: AU14NEMOInspector
  name: au14-job-name-corp-nemo-inspector
  description: au14-job-description-inspector
  whitelisted: true
  playTimeTracker: AU14JobNEMOInspector
  requirements:
  #- !type:RoleTimeRequirement
  #  role: AU14JobSquadRiflemanBase
  #  time: 108000 # 30 hours
  #- !type:RoleTimeRequirement
  #  role: AU14JobGOVFORMilitaryPoliceMan
  #  time: 108000 # 30 hours
  ranks:
    RMCRankProvostInspector: []
  startingGear: AU14GearNEMOInspector
  icon: AU14JobIconNEMOInspector
  joinNotifyCrew: true
  marineAuthorityLevel: 0
  supervisors: cm-job-supervisors-marine-high-command
  accessGroups:
  - ShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 2
        RMCSkillLeadership: 2
        RMCSkillMedical: 1
        RMCSkillOverwatch: 1
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-inspector
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: CommandAccent
    - type: RMCPointing
    - type: RMCTrackable
    - type: SeeNewPlayers
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: pve_chief_inspector
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_mp

- type: startingGear
  id: AU14GearNEMOInspector
  equipment:
    head: RMCHeadBeretProvostSenior
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvostSenior
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    id: RMCIDCardProvostInspector
    belt: RMCBeltHolsterPistolHandcannonFilled
    pocket1: RMCUniversalRecorder
    pocket2: RMCPouchGeneralLarge # TODO RMC14 3 listening devices

- type: playTimeTracker
  id: AU14JobNEMOInspector

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconNEMOInspector
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_lead_team

- type: entity
  parent: CMIDCardGold
  id: RMCIDCardNEMOInspector
  name: NEMO Inspector ID card
  description: Issued to members of the Nautical Examination Marshal's Office.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/provost.rsi
  - type: PresetIdCard
    job: AU14NEMOInspector
