- type: job
  parent: CMJobBase
  id: AU14NEMOAdvisor
  name: au14-job-name-corp-nemo-advisor
  description: au14-job-description-corp-nemo-advisor
  playTimeTracker: AU14JobNEMOAdvisor
  ranks:
    AU14RankNEMOAdvisor: []
  startingGear: AU14GearNEMOAdvisor
  icon: AU14JobIconNEMOAdvisor
  joinNotifyCrew: false
  accessGroups:
  - ShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 3
        RMCSkillEndurance: 2
        RMCSkillEngineer: 1
        RMCSkillOverwatch: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillVehicles: 1
        RMCSkillJtac: 1
        RMCSkillPolice: 2
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-advisor
    - type: RMCTrackable
  hidden: true

- type: entity
  id: AU14RandomHumanoidNEMOAdvisor
  name: provost ghost role advisor
  suffix: Spawner, Player, Friendly, Low Law Understanding
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: RandomHumanoidSpawner
    settings: AU14NEMOAdvisor

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: AU14NEMOAdvisor
  components:
  - type: GhostRole
    name: au14-job-name-corp-nemo-advisor
    description: au14-job-description-corp-nemo-advisor
    rules: au14-ghost-role-information-nemo-advisor-rules
    reregister: false
    job: AU14NEMOAdvisor
    raffle:
      settings: short
  - type: GhostRoleApplySpecial

- type: startingGear
  id: AU14GearNEMOAdvisor
  equipment:
    head: RMCHeadBeretProvostSenior
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvostSenior
    outerClothing: RMCProvostJacketFilled
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    id: RMCIDCardProvostAdvisor
    belt: CMBeltSecurityMPFilled
    back: CMSatchelSecurityFilledProvost
    pocket1: RMCUniversalRecorder
    pocket2: RMCPouchGeneralLarge # TODO RMC14 3 listening devices

- type: playTimeTracker
  id: AU14JobNEMOAdvisor

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconNEMOAdvisor
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_commander

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointProvostAdvisor
  name: NEMO Advisor spawn point
  components:
  - type: SpawnPoint
    job_id: AU14NEMOAdvisor
  - type: Sprite
    state: x # todo rmc14 need a spawn location sprite

- type: entity
  parent: CMIDCardGold
  id: RMCIDCardNEMOAdvisor
  name: NEMO Advisor ID card
  description: Issued to members of the Nautical Examination Marshal's Office.
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: Clothing
    slots:
    - idcard
    sprite: _RMC14/Objects/CMIDs/provost.rsi
  - type: PresetIdCard
    job: AU14NEMOAdvisor

