using Content.Client._CMU14.Interface;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsItemizedView : Control
{
    public RequisitionsItemizedView()
    {
        RobustXamlLoader.Load(this);
    }

    public void ApplyTheme()
    {
        CrtLobbyTheme.Apply(this, useCrtTypography: true);
        RootPanel.PanelOverride = Panel(CrtTerminalPalette.Surface0);
        StatusPanel.PanelOverride = Panel(CrtTerminalPalette.Surface3);
        FilterPanel.PanelOverride = Panel(CrtTerminalPalette.Surface1);
        CatalogPanel.PanelOverride = Panel(CrtTerminalPalette.Surface1);
        CartPanel.PanelOverride = Panel(CrtTerminalPalette.Surface1);
        CartSummaryPanel.PanelOverride = Panel(CrtTerminalPalette.Surface2);

        BudgetLabel.FontColorOverride = CrtTerminalPalette.TextBright;
        PlatformLabel.FontColorOverride = CrtTerminalPalette.Text;
        ResultCountLabel.FontColorOverride = CrtTerminalPalette.TextDim;
        FeedbackLabel.FontColorOverride = CrtTerminalPalette.Caution;

        CmuButtonStyles.Apply(ItemsTabButton, CmuButtonStyles.Variant.Affirm);
        CmuButtonStyles.Apply(BundlesTabButton, CmuButtonStyles.Variant.Neutral);
        CmuButtonStyles.Apply(PlatformButton, CmuButtonStyles.Variant.Neutral);
        CmuButtonStyles.Apply(CheckoutButton, CmuButtonStyles.Variant.Affirm);
    }

    private static StyleBoxFlat Panel(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0,
        };
    }
}
