using System.Linq;
using System.Numerics;
using Content.Client._CMU14.Interface;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._RMC14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsItemizedView : Control
{
    private const string ManifestPulseKey = "asrs-manifest-pulse";

    private static readonly Animation ManifestPulse = new()
    {
        Length = TimeSpan.FromSeconds(0.22),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White, 0f),
                    new AnimationTrackProperty.KeyFrame(CrtTerminalPalette.Accent, 0.09f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.13f),
                },
            },
        },
    };

    public RequisitionsItemizedView()
    {
        RobustXamlLoader.Load(this);
    }

    public void ApplyTheme()
    {
        CrtLobbyTheme.Apply(this, useCrtTypography: true);
        RootPanel.PanelOverride = Panel(CrtTerminalPalette.Surface0);
        StatusPanel.PanelOverride = Panel(CrtTerminalPalette.Surface3);
        FilterPanel.PanelOverride = Panel(CrtTerminalPalette.Surface1);
        CatalogPanel.PanelOverride = Panel(CrtTerminalPalette.Surface1);
        CartPanel.PanelOverride = Panel(CrtTerminalPalette.Surface1);
        CartSummaryPanel.PanelOverride = Panel(CrtTerminalPalette.Surface2);

        BudgetLabel.FontColorOverride = CrtTerminalPalette.TextBright;
        PlatformLabel.FontColorOverride = CrtTerminalPalette.Text;
        ResultCountLabel.FontColorOverride = CrtTerminalPalette.TextDim;
        FeedbackLabel.FontColorOverride = CrtTerminalPalette.Caution;

        CmuButtonStyles.Apply(ItemsTabButton, CmuButtonStyles.Variant.Affirm);
        CmuButtonStyles.Apply(BundlesTabButton, CmuButtonStyles.Variant.Neutral);
        CmuButtonStyles.Apply(PlatformButton, CmuButtonStyles.Variant.Neutral);
        CmuButtonStyles.Apply(CheckoutButton, CmuButtonStyles.Variant.Affirm);
    }

    public void PlayItemAddedAnimation(LayeredTextureRect source)
    {
        if (!source.IsInsideTree || !AnimationLayer.IsInsideTree)
            return;

        var iconSize = new Vector2(42, 42);
        var start = source.GlobalPosition - AnimationLayer.GlobalPosition;
        var targetCenter = CartPanel.GlobalPosition - AnimationLayer.GlobalPosition +
                           new Vector2(CartPanel.Width / 2f, 58);
        var end = targetCenter - iconSize / 2f;
        var flyout = new RequisitionsItemFlyout(source.Textures.ToList(), start, end, iconSize);
        flyout.Landed += PlayManifestPulse;
        AnimationLayer.AddChild(flyout);
    }

    private void PlayManifestPulse()
    {
        if (!CartPanel.IsInsideTree)
            return;

        if (CartPanel.HasRunningAnimation(ManifestPulseKey))
            CartPanel.StopAnimation(ManifestPulseKey);
        CartPanel.PlayAnimation(ManifestPulse, ManifestPulseKey);
    }

    private static StyleBoxFlat Panel(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0,
        };
    }
}
