using System.Linq;
using System.Numerics;
using Content.Client._CMU14.Interface;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.ControlExtensions;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsItemizedView : Control
{
    private const string ManifestPulseKey = "asrs-manifest-pulse";
    private const string CatalogPulseKey = "asrs-catalog-pulse";

    private float _checkoutSequence;
    private float _bootSequence;
    private string _receipt = string.Empty;
    private RequisitionsLayoutRefs _layout = default!;

    public event Action? ItemsRequested;
    public event Action? BundlesRequested;
    public event Action? PlatformRequested;
    public event Action? SearchChanged;
    public event Action? CheckoutRequested;
    public event Action? LayoutChanged;

    public RequisitionsTerminalStyle TerminalStyle { get; private set; }
    public RequisitionsTerminalTheme TerminalTheme => RequisitionsTerminalTheme.Get(TerminalStyle);
    public Control? PackingAnchor { get; set; }

    public PanelContainer RootPanel => _layout.RootPanel;
    public PanelContainer StatusPanel => _layout.StatusPanel;
    public PanelContainer FilterPanel => _layout.FilterPanel;
    public PanelContainer CatalogPanel => _layout.CatalogPanel;
    public PanelContainer CartPanel => _layout.CartPanel;
    public PanelContainer CartSummaryPanel => _layout.CartSummaryPanel;
    public PanelContainer PackingHintPanel => _layout.PackingHintPanel;
    public PanelContainer CheckoutStagePanel => _layout.CheckoutStagePanel;
    public PanelContainer ReceiptPanel => _layout.ReceiptPanel;
    public Label BudgetLabel => _layout.BudgetLabel;
    public Label ProjectedBudgetLabel => _layout.ProjectedBudgetLabel;
    public Label PlatformLabel => _layout.PlatformLabel;
    public Label ResultCountLabel => _layout.ResultCountLabel;
    public Label PackingHintLabel => _layout.PackingHintLabel;
    public Label CartStateLabel => _layout.CartStateLabel;
    public Label CartEmptyLabel => _layout.CartEmptyLabel;
    public Label CartCostLabel => _layout.CartCostLabel;
    public Label CartWeightLabel => _layout.CartWeightLabel;
    public Label CartCratesLabel => _layout.CartCratesLabel;
    public Label CartCapacityLabel => _layout.CartCapacityLabel;
    public Label FeedbackLabel => _layout.FeedbackLabel;
    public Label CheckoutPhaseLabel => _layout.CheckoutPhaseLabel;
    public Label ReceiptLabel => _layout.ReceiptLabel;
    public Label StyleSubtitleLabel => _layout.StyleSubtitleLabel;
    public Button ItemsTabButton => _layout.ItemsTabButton;
    public Button BundlesTabButton => _layout.BundlesTabButton;
    public Button PlatformButton => _layout.PlatformButton;
    public Button StyleButton => _layout.StyleButton;
    public Button CheckoutButton => _layout.CheckoutButton;
    public Button ReceiptDismissButton => _layout.ReceiptDismissButton;
    public LineEdit SearchBar => _layout.SearchBar;
    public BoxContainer CategoriesContainer => _layout.CategoriesContainer;
    public BoxContainer ItemsContainer => _layout.ItemsContainer;
    public BoxContainer CartContainer => _layout.CartContainer;
    public ProgressBar CheckoutProgress => _layout.CheckoutProgress;

    private static readonly Animation ManifestPulse = new()
    {
        Length = TimeSpan.FromSeconds(0.22),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White, 0f),
                    new AnimationTrackProperty.KeyFrame(CrtTerminalPalette.Accent, 0.09f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.13f),
                },
            },
        },
    };

    public RequisitionsItemizedView()
    {
        RobustXamlLoader.Load(this);
        LoadLayout();
    }

    private void LoadLayout()
    {
        var search = _layout?.SearchBar.Text ?? string.Empty;
        LayoutHost.RemoveAllChildren();
        Control layout = TerminalStyle switch
        {
            RequisitionsTerminalStyle.WeylandAmber => new RequisitionsManifestLayout(),
            RequisitionsTerminalStyle.ColonialCyan => new RequisitionsOperatorLayout(),
            RequisitionsTerminalStyle.UppRedline => new RequisitionsTacticalLayout(),
            RequisitionsTerminalStyle.FieldMono => new RequisitionsFieldLayout(),
            _ => new RequisitionsLoadBayLayout(),
        };
        layout.HorizontalExpand = true;
        layout.VerticalExpand = true;
        LayoutHost.AddChild(layout);
        _layout = new RequisitionsLayoutRefs(layout);
        SearchBar.Text = search;
        PackingAnchor = null;

        ItemsTabButton.OnPressed += _ => ItemsRequested?.Invoke();
        BundlesTabButton.OnPressed += _ => BundlesRequested?.Invoke();
        PlatformButton.OnPressed += _ => PlatformRequested?.Invoke();
        SearchBar.OnTextChanged += _ => SearchChanged?.Invoke();
        CheckoutButton.OnPressed += _ => CheckoutRequested?.Invoke();
        StyleButton.OnPressed += _ => CycleStyle();
        ReceiptDismissButton.OnPressed += _ => ReceiptPanel.Visible = false;
        ApplyTheme();
        _bootSequence = 0.001f;
    }

    public void ApplyTheme()
    {
        CrtLobbyTheme.Apply(this, useCrtTypography: true);
        var theme = TerminalTheme;
        foreach (var label in this.GetControlOfType<Label>(true))
            label.FontColorOverride = theme.Text;
        foreach (var scrollBar in this.GetControlOfType<ScrollBar>(true))
            scrollBar.RemoveStyleClass(StyleNano.StyleClassCrtScrollBar);
        SearchBar.RemoveStyleClass(StyleNano.StyleClassCrtLineEdit);
        SearchBar.RemoveStyleClass(StyleNano.StyleClassCrtNativeLineEdit);
        SearchBar.StyleBoxOverride = theme.Panel(theme.Background, corners: true);
        RootPanel.PanelOverride = theme.Panel(theme.Background, grid: TerminalStyle == RequisitionsTerminalStyle.WeylandAmber);
        StatusPanel.PanelOverride = theme.Panel(theme.SurfaceSelected);
        FilterPanel.PanelOverride = theme.Panel(theme.Surface);
        CatalogPanel.PanelOverride = theme.Panel(theme.Surface, grid: TerminalStyle == RequisitionsTerminalStyle.ColonialCyan);
        CartPanel.PanelOverride = theme.Panel(theme.Surface, corners: true);
        CartSummaryPanel.PanelOverride = theme.Panel(theme.SurfaceRaised);
        PackingHintPanel.PanelOverride = theme.Panel(theme.SurfaceRaised);
        CheckoutStagePanel.PanelOverride = theme.Panel(theme.SurfaceSelected, corners: true);
        ReceiptPanel.PanelOverride = theme.Panel(theme.SurfaceSelected, corners: true);

        BudgetLabel.FontColorOverride = theme.TextBright;
        ProjectedBudgetLabel.FontColorOverride = theme.Caution;
        PlatformLabel.FontColorOverride = theme.Text;
        ResultCountLabel.FontColorOverride = theme.TextDim;
        PackingHintLabel.FontColorOverride = theme.Accent;
        CartStateLabel.FontColorOverride = theme.Accent;
        FeedbackLabel.FontColorOverride = theme.Caution;
        CheckoutPhaseLabel.FontColorOverride = theme.TextBright;
        StyleSubtitleLabel.Text = theme.Name;
        StyleSubtitleLabel.FontColorOverride = theme.TextDim;
        StyleButton.Text = $"LAYOUT {(int) TerminalStyle + 1}/5  //  {theme.Subtitle}";
        CrtOverlay.SetProfile(TerminalStyle, theme.Accent);

        theme.ApplyButton(ItemsTabButton, primary: true);
        theme.ApplyButton(BundlesTabButton);
        theme.ApplyButton(PlatformButton);
        theme.ApplyButton(StyleButton, primary: true);
        theme.ApplyButton(CheckoutButton, primary: true);
        theme.ApplyButton(ReceiptDismissButton);

        CheckoutProgress.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = theme.Background };
        CheckoutProgress.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = theme.Accent };
    }

    public void CycleStyle()
    {
        TerminalStyle = RequisitionsTerminalTheme.Next(TerminalStyle);
        LoadLayout();
        LayoutChanged?.Invoke();
    }

    public void PlayItemAddedAnimation(LayeredTextureRect source)
    {
        if (!source.IsInsideTree || !AnimationLayer.IsInsideTree)
            return;

        var iconSize = new Vector2(42, 42);
        var start = source.GlobalPosition - AnimationLayer.GlobalPosition;
        var target = PackingAnchor is { IsInsideTree: true } ? PackingAnchor : CartPanel;
        var targetCenter = target.GlobalPosition - AnimationLayer.GlobalPosition + target.Size / 2f;
        var end = targetCenter - iconSize / 2f;
        var flyout = new RequisitionsItemFlyout(source.Textures.ToList(), start, end, iconSize);
        flyout.Landed += PlayManifestPulse;
        AnimationLayer.AddChild(flyout);
    }

    public void PlayItemRemovedAnimation(LayeredTextureRect source)
    {
        if (!source.IsInsideTree || !AnimationLayer.IsInsideTree)
            return;

        var iconSize = new Vector2(30, 30);
        var start = source.GlobalPosition - AnimationLayer.GlobalPosition;
        var targetCenter = CatalogPanel.GlobalPosition - AnimationLayer.GlobalPosition + new Vector2(CatalogPanel.Width / 2f, 52);
        var flyout = new RequisitionsItemFlyout(source.Textures.ToList(), start, targetCenter - iconSize / 2f, iconSize);
        flyout.Landed += PlayCatalogPulse;
        AnimationLayer.AddChild(flyout);
    }

    public void BeginCheckout()
    {
        ReceiptPanel.Visible = false;
        CheckoutStagePanel.Visible = true;
        CheckoutPhaseLabel.Text = Loc.GetString("cmu-asrs-phase-verifying");
        CheckoutProgress.Value = 0.12f;
        _checkoutSequence = -1f;
    }

    public void CompleteCheckout(string receipt)
    {
        _receipt = receipt;
        _checkoutSequence = 0.001f;
        CheckoutStagePanel.Visible = true;
    }

    public void PlayPurchasedItemsPacking()
    {
        var destination = CartPanel.GlobalPosition - AnimationLayer.GlobalPosition +
                          new Vector2(CartPanel.Width / 2f, CartPanel.Height - 72f);
        foreach (var icon in CartContainer.GetControlOfType<LayeredTextureRect>(true).Take(12))
        {
            if (!icon.IsInsideTree)
                continue;

            var size = new Vector2(28, 28);
            var start = icon.GlobalPosition - AnimationLayer.GlobalPosition;
            var flyout = new RequisitionsItemFlyout(icon.Textures.ToList(), start, destination - size / 2f, size);
            flyout.Landed += CrtOverlay.TriggerActivity;
            AnimationLayer.AddChild(flyout);
        }
    }

    public void RejectCheckout()
    {
        _checkoutSequence = 0;
        CheckoutStagePanel.Visible = false;
        CrtOverlay.TriggerGlitch();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_bootSequence > 0)
        {
            _bootSequence += args.DeltaSeconds;
            var progress = Math.Min(1f, _bootSequence / 0.28f);
            RootPanel.Modulate = Color.InterpolateBetween(TerminalTheme.Accent.WithAlpha(0.34f), Color.White, progress);
            if (progress >= 1f)
                _bootSequence = 0;
        }

        if (_checkoutSequence <= 0)
            return;

        _checkoutSequence += args.DeltaSeconds;
        CheckoutProgress.Value = Math.Min(1f, _checkoutSequence / 1.25f);
        CheckoutPhaseLabel.Text = Loc.GetString(_checkoutSequence switch
        {
            < 0.42f => "cmu-asrs-phase-packing",
            < 0.84f => "cmu-asrs-phase-sealing",
            < 1.25f => "cmu-asrs-phase-dispatching",
            _ => "cmu-asrs-phase-complete",
        });

        if (_checkoutSequence < 1.45f)
            return;

        _checkoutSequence = 0;
        CheckoutStagePanel.Visible = false;
        ReceiptLabel.Text = _receipt;
        ReceiptPanel.Visible = true;
    }

    private void PlayManifestPulse()
    {
        if (!CartPanel.IsInsideTree)
            return;

        if (CartPanel.HasRunningAnimation(ManifestPulseKey))
            CartPanel.StopAnimation(ManifestPulseKey);
        CartPanel.PlayAnimation(ManifestPulse, ManifestPulseKey);
        CrtOverlay.TriggerActivity();
    }

    private void PlayCatalogPulse()
    {
        if (!CatalogPanel.IsInsideTree)
            return;

        if (CatalogPanel.HasRunningAnimation(CatalogPulseKey))
            CatalogPanel.StopAnimation(CatalogPulseKey);
        CatalogPanel.PlayAnimation(ManifestPulse, CatalogPulseKey);
    }
}
