- type: job
  parent: CMJobBase
  id: AU14JobOpforSectionSergeant
  name: au14-job-name-opforSSG
  description: au14-job-description-opforSSG
  setPreference: true
  playTimeTracker: AU14JobOpforSectionSergeant
  ranks:
    RMCRankMasterSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobOpforSectionSergeant
      time: 7200 # 120 hours
    RMCRankGunnerySergeant:
    - !type:RoleTimeRequirement
      role: AU14JobOpforSectionSergeant
      time: 3600 # 60 hours
    RMCRankStaffSergeant: []
  startingGear: AU14GearOPFORSectionSergeant
  dummyStartingGear: AU14GearOPFORPlatoonSergantDummy
  icon: "AU14JobIconPlatoonSarge"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-OPFOR
  accessGroups:
  - SquadLeader
  overwatchSortPriority: -6
  overwatchShowName: true
  overwatchRoleName: Platoon Sergeant
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-OPFORSSG
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: false

- type: startingGear
  id: AU14GearOPFORSectionSergeant
  equipment:
    id: AU14OPFORSecSergeant

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORSectionSergeant
  name: Spawn Point OPFOR Section Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSectionSergeant
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobOpforSectionSergeant
  isHumanoid: true

- type: startingGear
  id: AU14GearOPFORPlatoonSergantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleTwo
    shoes: CMBootsBrown
    head: AU14JunglePatrolCap
    jumpsuit: AU14JungleFatigues
