- type: job
  parent: CMJobBase
  id: RMCJobSynthetic
  name: cm-job-name-liaison
  description: cm-job-description-liaison
  playTimeTracker: RMCJobSynthetic
  ranks:
    RMCRankSyntheticColonist: []
  startingGear: RMCGearSynthetic
  icon: "RMCJobIconSynth"
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  supervisors: cm-job-supervisors-co
  accessGroups:
  - ShipMasterAccess
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: synth
  minimapBackground:
   sprite: _RMC14/Interface/map_blips.rsi
   state: background_shipside
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 52.5 # 35 base damage, this is because they have melee weapons 2
    - type: Synth
      welderDamageToRepair:
        types:
          Blunt: -15
          Piercing: -15
          Slash: -15
      cableCoilDamageToRepair:
        types:
          Caustic: -15
          Heat: -15
          Shock: -15
          Cold: -15
      addComponents:
      # TODO darksight instead of night vision
      - type: NightVision
        innate: true
      - type: EyeProtection
      - type: WoundableUntreatable
      - type: Insulated
      removeComponents:
      - type: CMSurgeryTarget
      - type: Infectable
      - type: Hunger
      - type: Thirst
      - type: Perishable
      - type: ThermalRegulator
      - type: Stamina
      - type: DamageForceSay
      - type: Dna
      - type: InjectableSolution
      - type: IVDripTarget
    - type: Skills
      skills:
        RMCSkillCqc: 5
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        # RMCSkillFirearms: 2 -- Synths cant use firearms why the fuck do they get the highest skill??
        RMCSkillOverwatch: 1
        RMCSkillMedical: 4
        RMCSkillSurgery: 3
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 5
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 3
        RMCSkillIntel: 2
        RMCSkillDomestics: 2
        RMCSkillNavigations: 1
    - type: MarineOrders
#    - type: DemoSpecWhitelist -- THEY CAN USE EVERY SPEC TOO???
#    - type: GrenadeSpecWhitelist
#    - type: ScoutWhitelist
#    - type: SniperWhitelist
#    - type: PyroWhitelist
    - type: JobPrefix
      prefix: cm-job-prefix-liaison
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: RMCGearSynthetic
  equipment:
    jumpsuit: CMJumpsuitGeneral
    gloves: CMHandsInsulated
    shoes: RMCShoesWhite
    id: RMCIDCardFreelancer
    ears: RMCHeadsetSEA
    belt: CMBeltUtilityFilled

#- type: entity
#  parent: CMSpawnPointJobBase
#  id: RMCSpawnPointSynth
#  name: synthetic spawn point
#  components:
#  - type: SpawnPoint
#    job_id: RMCJobSynthetic
#  - type: Sprite
#    state: syn_spawn

- type: playTimeTracker
  id: RMCJobSynthetic
  isHumanoid: true

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSynth
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: hudsquad_syn


- type: rank
  id: RMCRankSyntheticColonist
  name: Synthetic
  prefix: Syn.
