- type: job
  parent: CMJobBase
  id: AU14IRGSynthetic
  name: au14-job-name-corp-nemo-irg-synthetic
  description: au14-job-description-corp-nemo-irg-synthetic
  playTimeTracker: AU14JobIRGSynthetic
  ranks:
    RMCRankProvostProvostEnforcer: []
  startingGear: AU14GearIRGSynthetic
  icon: AU14JobIconIRGSynthetic
  joinNotifyCrew: false
  accessGroups:
  - ShipMasterAccess
  spawnMenuRoleName: Provost Enforcer
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-enforcer
  hidden: true

- type: entity
  id: AU14RandomHumanoidIRGSynthetic
  name: provost ghost role enforcer
  suffix: Spawner, Player, Friendly
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: RandomHumanoidSpawner
    settings: AU14IRGSynthetic

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: AU14IRGSynthetic
  components:
  - type: GhostRole
    name: au14-ghost-name-corp-nemo-enforcer
    description: au14-job-description-corp-nemo-irg-synthetic
    rules: au14-ghost-role-information-nemo-rules
    reregister: false
    job: AU14IRGSynthetic
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORMilitaryPoliceMan
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORAuxSupportSynth
      time: 3600 # 1 Hour
  - type: GhostRoleApplySpecial
    squad: SquadProvost

- type: startingGear
  id: AU14GearIRGSynthetic
  equipment:
    head: RMCHeadBeretProvost
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvost
    outerClothing: RMCArmorProvost
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    suitstorage: WeaponShotgunM890
    id: RMCIDCardProvostEnforcer
    belt: RMCM1984BeltFilled
    back: CMSatchelSecurityFilledProvostEnforcer
    pocket1: RMCPouchShotgunLargeBeanbag
    pocket2: RMCPouchShotgunLargeSlugs # TODO RMC14 riot shield

- type: playTimeTracker
  id: AU14JobIRGSynthetic

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconIRGSynthetic
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_synth
