- type: job
  parent: CMJobBase
  id: AU14IRGMedic
  name: au14-job-name-corp-nemo-irg-medic
  description: au14-job-description-corp-nemo-irg-medic
  playTimeTracker: AU14JobIRGMedic
  ranks:
    AU14RankNEMOJuniorEnforcer: []
  startingGear: AU14GearIRGMedic
  icon: AU14JobIconIRGMedic
  joinNotifyCrew: false
  accessGroups:
  - AllAccess
  spawnMenuRoleName: NEMO IRG Medic
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-enforcer
  hidden: true

- type: entity
  id: AU14RandomHumanoidIRGMedic
  name: NEMO IRG ghost role medic
  suffix: Ghostrole, Neutral
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: RandomHumanoidSpawner
    settings: AU14IRGMedic

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: AU14IRGMedic
  components:
  - type: GhostRole
    name: au14-ghost-name-corp-nemo-medic
    description: au14-job-description-corp-nemo-irg-medic
    rules: au14-ghost-role-information-nemo-rules
    reregister: false
    job: AU14IRGMedic
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORMilitaryPoliceMan
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: AU14SquadIRG

- type: startingGear
  id: AU14GearIRGMedic
  equipment:
    head: RMCHeadBeretProvost
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvost
    outerClothing: RMCArmorProvost
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    suitstorage: WeaponShotgunM890
    id: RMCIDCardProvostEnforcer
    belt: RMCM1984BeltFilled
    back: CMSatchelSecurityFilledProvostEnforcer
    pocket1: RMCPouchShotgunLargeBeanbag
    pocket2: RMCPouchShotgunLargeSlugs # TODO RMC14 riot shield

- type: playTimeTracker
  id: AU14JobIRGMedic

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconIRGMedic
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_medic_lead
