- type: job
  parent: CMJobBase
  id: AU14JobGOVFORRadioTelephoneOoperator
  name: au14-job-name-radiotelephoneooperator
  description: au14-job-description-radiotelephoneooperator
  setPreference: true
  playTimeTracker: AU14JobGOVFORRadioTelephoneOoperator
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 3600 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 1800 # 30 hours
    RMCRankPrivateFirstClass: []
  startingGear: AU14GearGOVFORRadioTelephoneOoperator
  dummyStartingGear: AU14GearGOVFORRadioTelephoneOoperatorDummy
  icon: "AU14JobIconRTO"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - FTL
  overwatchSortPriority: -5
  overwatchRoleName: Radio Telephone Operator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-radiotelephoneooperator
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: false

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOoperator
  equipment:
    id: AU14JobIDCardGOVFORRadioTelephoneOoperator

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORRadioTelephoneOoperator
  name: Spawn Point GOVFOR Radio Telephone Ooperator
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORRadioTelephoneOoperator
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobGOVFORRadioTelephoneOoperator
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOoperatorDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues