using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    public Button CharacterSetupButton => CharacterSetup;
    public Button PrevCharacterButton => PrevCharButton;
    public Button NextCharacterButton => NextCharButton;
    public Button IgnoreAllegianceToggle => IgnoreAllegianceButton;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    public void SetJobText(string value)
    {
        JobSummary.Text = value;
        JobSummary.Visible = !string.IsNullOrWhiteSpace(value);
    }
}
