- type: job
  parent: CMJobBase
  id: AU14JobGOVFORDCCWYPMC
  name: PMC Crew Chief
  description: au14-job-description-govfordcc
  setPreference: false
  canBeAntag: false
  playTimeTracker: AU14JobGOVFORDCCWYPMC
  ranks:
    AU14RankWeYuSeniorCrewChief:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCCWYPMC
      time: 1800 # 30 hours
    AU14RankWeYuCrewChief: []
  startingGear: AU14GearGOVFORDCC
  dummyStartingGear: AU14GearGOVFORDCCDummy
  icon: "AU14JobIconDCC"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - augovforpilot
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: CRCHF
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: playTimeTracker
  id: AU14JobGOVFORDCCWYPMC
  isHumanoid: true