using Robust.Client.AutoGenerated;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._RMC14.Dialog;

[GenerateTypedNameReferences]
public sealed partial class RMCDialogWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IStylesheetManager _stylesheetManager = default!;

    public BoxContainer? Container;

    public RMCDialogWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshCrtTheme();
        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    public void RefreshCrtTheme()
    {
        Stylesheet = _stylesheetManager.SheetNanotrasen;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        RefreshCrtTheme();
    }

    private void OnCrtUiColorChanged(string _)
    {
        RefreshCrtTheme();
    }
}
