using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Dialog;

[GenerateTypedNameReferences]
public sealed partial class RMCDialogOptionsContainer : BoxContainer
{
    [Dependency] private IGameTiming _timing = default!;

    private TimeSpan? _expiresAt;

    public RMCDialogOptionsContainer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetCountdown(TimeSpan? expiresAt)
    {
        _expiresAt = expiresAt;
        UpdateCountdown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCountdown();
    }

    private void UpdateCountdown()
    {
        Countdown.Visible = _expiresAt != null;
        if (_expiresAt is not { } expiresAt)
            return;

        var remaining = Math.Max(0, (int) Math.Ceiling((expiresAt - _timing.CurTime).TotalSeconds));
        Countdown.Text = Loc.GetString("rmc-dialog-time-remaining", ("seconds", remaining));
    }
}
