using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Kitchen;
using Content.Shared.Kitchen.Components;
using Content.Shared.Kitchen.EntitySystems;
using Content.Shared.Power.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Kitchen.UI;

[GenerateTypedNameReferences]
public sealed partial class GrinderMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly ItemSlotsSystem _slots = default!;
    private readonly SharedPowerReceiverSystem _power = default!;
    private readonly SharedReagentGrinderSystem _grinder = default!;
    private readonly SharedSolutionContainerSystem _solutionContainer = default!;

    private readonly Dictionary<int, EntityUid> _chamberVisualContents = new();
    private readonly StyleBoxFlat _reagentPanel = new() { BackgroundColor = Color.FromHex("#373744") };
    private EntityUid _owner;

    public event Action? OnToggleAuto;
    public event Action? OnGrind;
    public event Action? OnJuice;
    public event Action? OnLink;
    public event Action? OnEjectAll;
    public event Action? OnEjectBeaker;
    public event Action<EntityUid>? OnEjectChamber;
    public event Action<ReagentQuantity>? OnBottle;
    public event Action<ReagentQuantity>? OnDisposeReagent;

    public GrinderMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _slots = _entityManager.System<ItemSlotsSystem>();
        _power = _entityManager.System<SharedPowerReceiverSystem>();
        _grinder = _entityManager.System<SharedReagentGrinderSystem>();
        _solutionContainer = _entityManager.System<SharedSolutionContainerSystem>();

        AutoModeButton.OnPressed += _ => OnToggleAuto?.Invoke();
        GrindButton.OnPressed += _ => OnGrind?.Invoke();
        JuiceButton.OnPressed += _ => OnJuice?.Invoke();
        LinkButton.OnPressed += _ => OnLink?.Invoke();
        ChamberContentBox.EjectButton.OnPressed += _ => OnEjectAll?.Invoke();
        BeakerContentBox.EjectButton.OnPressed += _ => OnEjectBeaker?.Invoke();
        ChamberContentBox.BoxContents.OnItemSelected += OnChamberBoxContentsItemSelected;
        BeakerContentBox.BoxContents.SelectMode = ItemList.ItemListSelectMode.None;
    }

    private void OnChamberBoxContentsItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        OnEjectChamber?.Invoke(_chamberVisualContents[args.ItemIndex]);
    }

    /// <summary>
    ///     Set the reagent grinder entity associated with this menu.
    /// </summary>
    /// <param name="owner">The reagent grinder.</param>
    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
        UpdateUi();
    }

    /// <summary>
    ///     Update the UI state of this reagent grinder, including its contents,
    ///     current grinding/juicing status, and button toggle states.
    /// </summary>
    public void UpdateUi()
    {
        if (!_entityManager.TryGetComponent<ReagentGrinderComponent>(_owner, out var grinderComp))
            return;

        var active = _grinder.IsActive((_owner, grinderComp));
        var beaker = _slots.GetItemOrNull(_owner, ReagentGrinderComponent.BeakerSlotId);
        var powered = _power.IsPowered(_owner);
        var hasInput = grinderComp.InputContainer.ContainedEntities.Any();
        var canGrind = hasInput && grinderComp.InputContainer.ContainedEntities.All(x => _grinder.CanGrind(x));
        var canJuice = hasInput && grinderComp.InputContainer.ContainedEntities.All(x => _grinder.CanJuice(x));

        BeakerContentBox.EjectButton.Disabled = active || !beaker.HasValue;
        ChamberContentBox.EjectButton.Disabled = active || !hasInput;
        GrindButton.Disabled = active || !canGrind || !powered || !beaker.HasValue;
        JuiceButton.Disabled = active || !canJuice || !powered || !beaker.HasValue;
        LinkButton.Disabled = active || !powered || grinderComp.SmartFridge != null;
        GrindButton.Modulate = grinderComp.Program == GrinderProgram.Grind ? Color.Green : Color.White;
        JuiceButton.Modulate = grinderComp.Program == GrinderProgram.Juice ? Color.Green : Color.White;

        AutoModeButton.Text = grinderComp.AutoMode switch
        {
            GrinderAutoMode.Grind => Loc.GetString("grinder-menu-grind-button"),
            GrinderAutoMode.Juice => Loc.GetString("grinder-menu-juice-button"),
            _ => Loc.GetString("grinder-menu-auto-button-off"),
        };

        //Refresh chamber contents
        _chamberVisualContents.Clear();

        ChamberContentBox.BoxContents.Clear();
        foreach (var entity in grinderComp.InputContainer.ContainedEntities)
        {
            // TODO: Replace with SpriteView
            var texture = _entityManager.GetComponent<SpriteComponent>(entity).Icon?.Default;
            var solidItem = ChamberContentBox.BoxContents.AddItem(_entityManager.GetComponent<MetaDataComponent>(entity).EntityName, texture);
            var solidIndex = ChamberContentBox.BoxContents.IndexOf(solidItem);
            _chamberVisualContents.Add(solidIndex, entity);
        }

        //Refresh beaker contents
        BeakerContentBox.BoxContents.Clear();
        BeakerContentBox.BoxContents.Visible = false;
        ReagentBoxContents.RemoveAllChildren();
        //if no beaker is attached use this guard to prevent hitting a null reference.
        if (!beaker.HasValue || !_solutionContainer.TryGetFitsInDispenser(beaker.Value, out _, out var reagents))
            return;

        //Looks like we have a beaker attached.
        if (!reagents.Any())
        {
            return;
        }
        else
        {
            foreach (var (reagent, quantity) in reagents)
            {
                var reagentName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                    ? $"{quantity} {proto.LocalizedName}"
                    : "???";
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                };
                row.AddChild(new Label { Text = reagentName });

                if (grinderComp.SmartFridge != null)
                {
                    var reagentQuantity = new ReagentQuantity(reagent, quantity);
                    var bottle = new Button { Text = Loc.GetString("grinder-menu-bottle") };
                    bottle.OnPressed += _ => OnBottle?.Invoke(reagentQuantity);
                    row.AddChild(bottle);

                    var dispose = new Button
                    {
                        Modulate = Color.Red,
                        Text = Loc.GetString("grinder-menu-dispose"),
                    };
                    dispose.OnPressed += _ => OnDisposeReagent?.Invoke(reagentQuantity);
                    row.AddChild(dispose);
                }

                var panel = new PanelContainer { PanelOverride = _reagentPanel };
                panel.AddChild(row);
                ReagentBoxContents.AddChild(panel);
            }
        }
    }
}
