- type: job
  parent: CMJobBase
  id: AU14MIGExaminer
  name: au14-job-name-corp-nemo-mig-examiner
  description: au14-job-description-corp-nemo-mig-examiner
  playTimeTracker: AU14JobMIGExaminer
  ranks:
    RMCRankProvostProvostEnforcer: []
  startingGear: AU14GearMIGExaminer
  icon: AU14JobIconMIGExaminer
  joinNotifyCrew: false
  accessGroups:
  - ShipMasterAccess
  spawnMenuRoleName: Provost Enforcer
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillEndurance: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-nemo-mig-examiner
  hidden: true

- type: entity
  id: AU14RandomHumanoidMIGExaminer
  name: provost ghost role enforcer
  suffix: Spawner, Player, Friendly
  components:
  - type: Sprite
    sprite: _RMC14/Objects/CMIDs/provost.rsi
    state: provost
  - type: RandomHumanoidSpawner
    settings: AU14MIGExaminer

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: AU14MIGExaminer
  components:
  - type: GhostRole
    name: au14-ghost-name-corp-nemo-mig-examiner
    description: au14-job-description-corp-nemo-mig-examiner
    rules: au14-ghost-role-information-nemo-rules
    reregister: false
    job: AU14MIGExaminer
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 18000 # 5 Hours
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORMilitaryPoliceMan
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: AU14SquadMIG

- type: startingGear
  id: AU14GearMIGExaminer
  equipment:
    head: RMCHeadBeretProvost
    eyes: CMGlassesSecurity
    ears: AU14HeadsetNEMO
    ears2: RMCM5CameraGear
    jumpsuit: CMJumpsuitProvost
    outerClothing: RMCArmorProvost
    gloves: CMHandsBlackMarine # TODO RMC14 black gloves
    shoes: CMBootsBlackFilled
    suitstorage: WeaponShotgunM890
    id: RMCIDCardProvostEnforcer
    belt: RMCM1984BeltFilled
    back: CMSatchelSecurityFilledProvostEnforcer
    pocket1: RMCPouchShotgunLargeBeanbag
    pocket2: RMCPouchShotgunLargeSlugs # TODO RMC14 riot shield

- type: playTimeTracker
  id: AU14JobMIGExaminer

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconMIGExaminer
  icon:
    sprite: _AU14/Interface/job_icons.rsi
    state: hudsquad_nemo_clear_blank
