- type: rank
  id: RMCRankCivilian
  name: Civilian
  prefix: Civ.
  malePrefix: Mr.
  femalePrefix: Ms.

- type: rank
  id: RMCRankCivilianNurse
  name: Nurse
  prefix: Nrs.

- type: rank
  id: RMCRankCivilianDoctor
  name: Doctor
  prefix: Dr.

- type: rank
  id: RMCRankCivilianProfessor
  name: Professor
  prefix: Prof.

- type: rank
  id: RMCRankCivilianRepresentative
  name: Representative
  prefix: Rep.

- type: rank
  id: RMCRankCivilianOfficer
  name: Officer
  prefix: Off.

- type: rank
  id: RMCRankCivilianSeniorOfficer
  name: Senior Officer
  prefix: Sr. Off.

- type: rank
  id: RMCRankCivilianAdministrator
  name: Administrator
  prefix: Admin.

- type: rank
  id: RMCRankCivilianSeniorAdministrator
  name: Senior Administrator
  prefix: Sr. Admin.

- type: rank
  id: RMCRankCivilianParkRanger
  name: Ranger
  prefix: Rngr.

- type: rank
  id: RMCRankCivilianSeniorParkRanger
  name: Senior Ranger
  prefix: Sr. Rngr.

- type: rank
  id: RMCRankCivilianCMBDeputy
  name: Probationary Deputy Marshal
  prefix: Prob. Dep.

- type: rank
  id: RMCRankCivilianCMBDeputy
  name: Deputy Marshal
  prefix: Dep.

- type: rank
  id: RMCRankCivilianSeniorCMBDeputy
  name: Senior Deputy Marshal
  prefix: Sr. Dep.

- type: rank
  id: RMCRankCivilianCMBMarshal
  name: Marshal
  prefix: Mshl.