- type: job
  parent: CMJobBase
  id: AU14PlatoonOperationsOfficer
  name: cm-job-name-platoon-operations-officer
  description: cm-job-description-platoon-operations-officer
  setPreference: false
  playTimeTracker: AU14JobPlatoonOperationsOfficer
  ranks:
    RMCRankSecondLT: []
  weight: 5
  startingGear: CMGearRifleman
  icon: "CMJobIconStaffOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-platco
  accessGroups:
  - MarineMain
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: so
  minimapBackground:
   sprite: _RMC14/Interface/map_blips.rsi
   state: background_command
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 3
        RMCSkillLeadership: 2
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPolice: 1
        RMCSkillPowerLoader: 1
        RMCSkillVehicles: 1
    - type: MarineOrders
    - type: CMVendorUser
      points: 45
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-platoon-operations-officer
    - type: ViewIntelObjectives
    - type: CommandAccent

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14PlatoonOperationsOfficerSpawnPoint
  name: platoon operations officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMStaffOfficer
  - type: Sprite
    state: so_spawn

- type: playTimeTracker
  id: AU14PlatoonOperationsOfficer
  isHumanoid: true
